# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
random_tensor_A = torch.rand(7, 7)
random_tensor_A.shape

torch.Size([7, 7])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
random_tensor_B = torch.rand(1, 7)

In [4]:
# Perform matrix multiplication 
torch.matmul( random_tensor_A, random_tensor_B.T )

tensor([[1.1831],
        [1.0714],
        [0.6838],
        [1.5570],
        [1.6265],
        [0.9915],
        [1.2672]])

In [5]:
torch.matmul( random_tensor_B, random_tensor_A ) # different values and vector output

tensor([[1.4762, 1.0353, 0.9586, 1.3562, 1.0858, 1.4495, 1.1026]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [6]:
import random

In [7]:
# Set manual seed
RANDOM_SEED=0 
torch.manual_seed(seed=RANDOM_SEED) 

In [8]:
# Create two random tensors
random_tensor_a = torch.rand(7, 7)
random_tensor_b = torch.rand(1, 7)

In [9]:
# Matrix multiply tensors
torch.matmul( random_tensor_a, random_tensor_b.T )

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

__Note:__ Need NVidia GPU to run this code. Otherwise, must use CPU-only.   

See: https://pytorch.org/docs/stable/generated/torch.cuda.manual_seed.html

In [10]:
# Set random seed on the GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

if device == "cuda":
    torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [11]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
is_gpu = torch.cuda.is_available()

# Create two random tensors on GPU
random_tensor_c = torch.rand(2, 3)
random_tensor_d = torch.rand(2, 3)

random_tensor_c.to(device)
random_tensor_d.to(device)

tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])

In [12]:
print(is_gpu)

False



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [13]:
# Perform matmul on tensor_A and tensor_B
mul_tensor = torch.matmul( random_tensor_c, random_tensor_d.T )
mul_tensor

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])

### 8. Find the maximum and minimum values of the output of 7.

In [14]:
# Find max
print( "max: ", torch.max(mul_tensor) )

max:  tensor(0.5617)


In [15]:
# Find min
print( "min: ", torch.min(mul_tensor) )

min:  tensor(0.3647)


### 9. Find the maximum and minimum index values of the output of 7.

In [16]:
# Find arg max
print( "max: ", torch.argmax(mul_tensor) )

max:  tensor(3)


In [17]:
# Find arg min
print( "max: ", torch.argmin(mul_tensor) )

max:  tensor(0)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [18]:
# Set seed
RANDOM_SEED=7 
torch.manual_seed(seed=RANDOM_SEED) 

In [19]:
# Create random tensor
random_tensor_e = torch.rand(1, 1, 1, 10)

In [20]:
# Remove single dimensions
flat_tensor = random_tensor_e.squeeze()

In [21]:
# Print out tensors and their shapes
print( random_tensor_e )
print( random_tensor_e.shape )

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
torch.Size([1, 1, 1, 10])


In [23]:
print( flat_tensor )
print( flat_tensor.shape )

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])
